development:
  dialect: postgres
  datasource: host={DB_HOST} user={DB_USER} password={DB_PASSWORD} dbname={DB_DBNAME} port={DB_PORT} sslmode={DB_SSL_MODE} TimeZone=Asia/Bangkok
  dir: database/migrations
  table: migrations
